import { describe,it,expect } from 'vitest';
import { brushSegment, appendBrush, brushForce, rayTriangleDistance, springStep } from '../src/brush';
describe('depth sculptural brush',()=>{
 it('keeps an immutable eight-segment continuous history',()=>{let history: ReturnType<typeof appendBrush>=[];for(let i=0;i<12;i++){const previous=history;history=appendBrush(history,brushSegment([i,0,0],[i+1,0,0],2,i));expect(previous).not.toBe(history);}expect(history).toHaveLength(8);expect(history[0].start[0]).toBe(4);});
 it('varies radius within the chosen range and rejects invalid coordinates',()=>{expect(brushSegment([0,0,0],[0,0,0],0,0).radius).toBe(.35);expect(brushSegment([0,0,0],[1,0,0],99,0).radius).toBeCloseTo(.65);expect(()=>brushSegment([NaN,0,0],[0,0,0],1,0)).toThrow();});
 it('selects real front triangle depth and misses outside surface',()=>{expect(rayTriangleDistance([0,0,3],[0,0,-1],[-1,-1,0],[1,-1,0],[0,1,0])).toBeCloseTo(3);expect(rayTriangleDistance([5,0,3],[0,0,-1],[-1,-1,0],[1,-1,0],[0,1,0])).toBeNull();expect(rayTriangleDistance([0,0,3],[1,0,0],[-1,-1,0],[1,-1,0],[0,1,0])).toBeNull();});
 it('pulls along the whole sweep with finite bounded forces and weaker depth',()=>{const segment=brushSegment([-1,0,0],[1,0,0],4,0);const front=brushForce([0,0,0],[segment],0,[0,0,-1]);const back=brushForce([0,0,-.3],[segment],0,[0,0,-1]);expect(front.every(Number.isFinite)).toBe(true);expect(Math.hypot(...front)).toBeGreaterThan(Math.hypot(...back));expect(Math.hypot(...front)).toBeLessThanOrEqual(100);expect(brushForce([0,0,0],[segment],2,[0,0,-1])).toEqual([0,0,0]);});
 it('caps energy and restores within two seconds with timestep continuity',()=>{let state={position:[.8,0,0] as const,velocity:[0,0,0] as const};for(let i=0;i<120;i++)state=springStep(state,[0,0,0],1/60);expect(Math.hypot(...state.position)).toBeLessThan(.003);expect(springStep({position:[0,0,0],velocity:[100,0,0]},[999,0,0],.05).position[0]).toBeLessThanOrEqual(.8);});
});
import { bridgeBrush, validBrushSegments } from '../src/brush';
describe('surface continuity and input boundaries',()=>{
 it('never joins different surfaces or large jumps',()=>{expect(bridgeBrush({point:[0,1,0],target:'horse'},[1,0,2],'terrain')).toEqual([1,0,2]);expect(bridgeBrush({point:[0,0,0],target:'terrain'},[3,0,0],'terrain')).toEqual([3,0,0]);expect(bridgeBrush({point:[0,0,0],target:'horse'},[.7,0,0],'horse')).toEqual([0,0,0]);expect(bridgeBrush(undefined,[.7,0,0],'horse')).toEqual([.7,0,0]);});
 it('filters externally invalid segments and caps accepted strengths',()=>{const s=brushSegment([0,0,0],[1,0,0],4,0);expect(validBrushSegments([{...s,radius:NaN},{...s,strength:Infinity},{...s,start:[NaN,0,0]},{...s,radius:-1},{...s,strength:5}],0)).toEqual([{...s,strength:1}]);});
 it('returns continuously with smaller timesteps and handles invalid states',()=>{const initial={position:[.4,.2,0] as const,velocity:[0,0,0] as const};let a=initial,b=initial;for(let i=0;i<60;i++)a=springStep(a,[0,0,0],1/60);for(let i=0;i<120;i++)b=springStep(b,[0,0,0],1/120);expect(Math.hypot(...a.position.map((v,i)=>v-b.position[i]))).toBeLessThan(.003);expect(()=>springStep({position:[NaN,0,0],velocity:[0,0,0]},[0,0,0],.01)).toThrow();});
});
