import {describe,it,expect} from 'vitest';
import {dirtLaunch,dirtPoint,dirtPigment} from '../src/dirt';
import {worldHeight} from '../src/terrain';
describe('soil clods',()=>{
 it('uses predominantly low clods with scrape and sparse tall grain populations',()=>{let low=0,scrape=0,tall=0;for(let i=0;i<1000;i++){const p=dirtLaunch(i/1000,1);expect(p.x).toBeLessThan(0);if(p.y<1.2)scrape++;else if(p.y<=3)low++;else tall++;}expect(scrape).toBe(200);expect(low).toBe(650);expect(tall).toBe(150);});
 it('launches from actual terrain and settles on advected hills',()=>{const hit={x:.5,z:.2,born:2,strength:.8};for(const seed of [.05,.7,.9]){const p=dirtPoint(hit,0,seed);expect(p.y).toBeCloseTo(worldHeight(hit.x,hit.z,hit.born)+.004);const settled=dirtPoint(hit,1.5,seed);expect(settled.y).toBeCloseTo(worldHeight(settled.x,settled.z,3.5)+.002);expect(settled.x).toBeLessThan(hit.x-9);expect(Object.values(settled).every(Number.isFinite)).toBe(true);}});
 it('pigments fragments green or warm earth without white bleaching',()=>{for(let i=0;i<100;i++){const c=dirtPigment(i/100);expect(c.every(v=>Number.isFinite(v)&&v>=0&&v<.5)).toBe(true);}expect(dirtPigment(.9)[0]).toBeGreaterThan(dirtPigment(.9)[2]);});
 it('rejects invalid coordinates, energy and lifetime inputs',()=>{expect(()=>dirtPoint({x:NaN,z:0,born:0,strength:1},.2,.2)).toThrow();expect(()=>dirtLaunch(.2,Infinity)).toThrow();expect(()=>dirtPoint({x:0,z:0,born:0,strength:1},-.1,.2)).toThrow();expect(()=>dirtPigment(2)).toThrow();});
});
it('settled clods retain fixed material coordinates instead of sliding like fluid',()=>{const hit={x:.5,z:.2,born:2,strength:.9};for(const seed of [.04,.45,.9]){const a=dirtPoint(hit,1.3,seed),b=dirtPoint(hit,2.1,seed);expect(a.x+6*(hit.born+1.3)).toBeCloseTo(b.x+6*(hit.born+2.1),9);expect(a.z).toBeCloseTo(b.z,9);expect(a.y).toBeCloseTo(worldHeight(a.x,a.z,3.3)+.002);}});
it('breaks seed-ordered launch bands with independent three-axis variation',()=>{const velocities=Array.from({length:40},(_,i)=>dirtLaunch(.3+i*.001,1));const differences=velocities.slice(1).map((v,i)=>({x:Math.abs(v.x-velocities[i].x),y:Math.abs(v.y-velocities[i].y),z:Math.abs(v.z-velocities[i].z)}));expect(differences.filter(d=>d.y>.08).length).toBeGreaterThan(25);expect(differences.filter(d=>d.x>.12).length).toBeGreaterThan(25);expect(differences.filter(d=>d.z>.035).length).toBeGreaterThan(25);});
