import {readFileSync} from 'node:fs';
import {describe,it,expect} from 'vitest';
import {decodeEquine} from '../src/equine';
import {extractHooves,hoofAt,GROUND_SPEED} from '../src/forces';
import {createContactTimeline} from '../src/contacts';
import {refineGait,stanceCorrection} from '../src/gait-refinement';
const metadata=JSON.parse(readFileSync('public/equine/metadata.json','utf8'));
const float=readFileSync('public/equine/frames.f32'),index=readFileSync('public/equine/topology.u32');
const source=decodeEquine(metadata,new Float32Array(float.buffer.slice(float.byteOffset,float.byteOffset+float.byteLength)),new Uint32Array(index.buffer.slice(index.byteOffset,index.byteOffset+index.byteLength)));
describe('one natural grounded stride',()=>{
 it('retains topology, duration and finite immutable authored anatomy',()=>{const before=source.positions.slice(),mesh=refineGait(source);expect(mesh.positions).not.toBe(source.positions);expect(source.positions).toEqual(before);expect(mesh.topology).toBe(source.topology);expect(mesh.cycleSeconds).toBe(.9);expect(mesh.frameCount).toBe(24);expect(mesh.positions.every(Number.isFinite)).toBe(true);});
 it('has one support interval per hoof and four distinct contacts',()=>{const mesh=refineGait(source),tracks=extractHooves(mesh),timeline=createContactTimeline(mesh);expect(timeline.strikes).toHaveLength(4);expect(new Set(timeline.strikes.map(s=>s.phase.toFixed(2))).size).toBe(4);for(const track of tracks){const states=Array.from({length:240},(_,i)=>hoofAt(mesh,track,i*.9/240).y<track.floor+.04);const starts=states.filter((value,i)=>value&&!states[(i+239)%240]);expect(starts.length).toBe(1);}});
 it('plants each sole during its central support phase and carries it with the bed',()=>{const mesh=refineGait(source),tracks=extractHooves(mesh),timeline=createContactTimeline(mesh);for(const strike of timeline.strikes){const time=strike.phase+strike.contactDuration*.45,point=hoofAt(mesh,tracks[strike.hoof],time),later=hoofAt(mesh,tracks[strike.hoof],time+.002);expect(point.y).toBeLessThan(.035);expect(Math.abs((later.x-point.x)/.002+GROUND_SPEED)).toBeLessThan(2);}});
 it('bounds stance changes and fades at liftoff and landing',()=>{expect(stanceCorrection(0,.18,.12,.3,.4)).toEqual({x:0,y:0});expect(stanceCorrection(.18,.18,.12,.3,.4)).toEqual({x:0,y:0});const middle=stanceCorrection(.09,.18,.12,.3,.4);expect(Math.abs(middle.x)).toBeLessThanOrEqual(.16);expect(Math.abs(middle.y)).toBeLessThanOrEqual(.085);expect(()=>stanceCorrection(NaN,.18,.12,.3,.4)).toThrow();});
 it('preserves authored upper joint geometry and bounds lower limb edge distortion',()=>{const mesh=refineGait(source),errors:number[]=[];for(let frame=0;frame<12;frame++){const authored=(frame+12)*source.vertexCount*3,corrected=frame*2*mesh.vertexCount*3;for(let triangle=0;triangle<source.topology.length;triangle+=30){const a=source.topology[triangle],b=source.topology[triangle+1];const length=(positions:Float32Array,offset:number)=>Math.hypot(...[0,1,2].map(axis=>positions[offset+a*3+axis]-positions[offset+b*3+axis]));const original=length(source.positions,authored);if(original>.001&&source.positions[authored+a*3+1]<.85&&source.positions[authored+b*3+1]<.85)errors.push(Math.abs(length(mesh.positions,corrected)/original-1));}}expect(errors.reduce((sum,error)=>sum+error,0)/errors.length).toBeLessThan(.03);errors.sort((a,b)=>a-b);expect(errors[Math.floor(errors.length*.95)]).toBeLessThan(.05);});
 it('maintains a finite smooth periodic interpolation through the frame seam',()=>{const mesh=refineGait(source),tracks=extractHooves(mesh);for(const track of tracks){const a=hoofAt(mesh,track,-.0001),b=hoofAt(mesh,track,.0001);expect(Math.hypot(a.x-b.x,a.y-b.y,a.z-b.z)).toBeLessThan(.004);}});
});
