import {describe,it,expect} from 'vitest';
import {materialHeight,worldHeight,terrainNormal,horseTerrainPose,transformTerrainPoint} from '../src/terrain';
describe('rolling material terrain',()=>{
 it('is deterministic periodic and bounded with gentle finite slopes',()=>{for(let x=-40;x<40;x+=.41)for(let z=-10;z<10;z+=.77){const h=materialHeight(x,z);expect(h).toBe(materialHeight(x,z));expect(materialHeight(x+36,z)).toBeCloseTo(h,10);expect(Math.abs(h)).toBeLessThan(.35);const n=terrainNormal(x,z);expect(Math.hypot(n.x,n.y,n.z)).toBeCloseTo(1,10);expect(Math.hypot(n.x,n.z)/n.y).toBeLessThan(.14);}});
 it('advects one continuous height field without wrap jumps',()=>{for(let t=0;t<6;t+=.1){expect(worldHeight(2,1,t)).toBeCloseTo(materialHeight(2+6*t,1),10);expect(worldHeight(2,1,t+6)).toBeCloseTo(worldHeight(2,1,t),10);expect(Math.abs(worldHeight(2,1,t+.0001)-worldHeight(2,1,t))).toBeLessThan(.001);}});
 it('aligns horse rigid pose to centre slope and preserves point distances',()=>{for(let t=0;t<6;t+=.2){const pose=horseTerrainPose(t), root=transformTerrainPoint({x:0,y:0,z:0},t), a=transformTerrainPoint({x:1,y:2,z:.3},t);expect(root.y).toBeCloseTo(worldHeight(0,0,t),10);expect(Math.abs(pose.pitch)).toBeLessThan(.14);expect(Math.hypot(a.x-root.x,a.y-root.y,a.z-root.z)).toBeCloseTo(Math.hypot(1,2,.3),10);expect((worldHeight(.001,0,t)-worldHeight(-.001,0,t))/.002).toBeCloseTo(Math.tan(pose.pitch),5);}});
 it('rejects nonfinite public inputs',()=>{expect(()=>materialHeight(NaN,0)).toThrow();expect(()=>worldHeight(0,0,Infinity)).toThrow();expect(()=>horseTerrainPose(NaN)).toThrow();expect(()=>transformTerrainPoint({x:NaN,y:0,z:0},0)).toThrow();});
});
it('transforms animated mesh arrays consistently with individual GPU pose anchors',async()=>{const {transformTerrainVertices}=await import('../src/terrain');const source=new Float32Array([0,0,0,1,2,.2,-1,.4,-.3]);const result=transformTerrainVertices(source,1.2);expect(source).toEqual(new Float32Array([0,0,0,1,2,.2,-1,.4,-.3]));for(let i=0;i<source.length;i+=3){const p=transformTerrainPoint({x:source[i],y:source[i+1],z:source[i+2]},1.2);expect(result[i]).toBeCloseTo(p.x,6);expect(result[i+1]).toBeCloseTo(p.y,6);expect(result[i+2]).toBeCloseTo(p.z,6);}expect(()=>transformTerrainVertices(new Float32Array([1]),0)).toThrow();});
it('aligns grounded lower limbs to curved terrain without bending upper anatomy',()=>{for(let t=0;t<6;t+=.15){for(const x of [-1.5,-1,1,1.5]){const foot=transformTerrainPoint({x,y:0,z:.25},t);expect(foot.y).toBeCloseTo(worldHeight(foot.x,foot.z,t),5);const elevated=transformTerrainPoint({x,y:1,z:.25},t),pose=horseTerrainPose(t);expect(elevated.y).toBeCloseTo(Math.sin(pose.pitch)*x+Math.cos(pose.pitch)+pose.height,10);}}});
