import { describe,it,expect,vi } from 'vitest';
import * as THREE from 'three';
import { generateWind,createWind } from '../src/wind';
describe('wind stream generation',()=>{
 it('generates deterministic seeded streams',()=>{expect(generateWind(128,71)).toEqual(generateWind(128,71));expect(generateWind(128,71).positions).not.toEqual(generateWind(128,72).positions);});
 it('keeps six finite peripheral stream anchors and bounded phases',()=>{const cloud=generateWind(2048);expect(cloud.positions).toHaveLength(6144);expect(cloud.phases).toHaveLength(2048);const streams=new Set<number>();for(let i=0;i<2048;i++){streams.add(cloud.streams[i]);expect(cloud.positions[i*3]).toBeGreaterThanOrEqual(-18);expect(cloud.positions[i*3]).toBeLessThan(18);expect(cloud.positions[i*3+1]).toBeGreaterThanOrEqual(.05);expect(cloud.positions[i*3+1]).toBeLessThanOrEqual(1.5);expect(Math.abs(cloud.positions[i*3+2])).toBeGreaterThan(.55);expect(Math.abs(cloud.positions[i*3+2])).toBeLessThan(5);expect(cloud.phases[i]).toBeGreaterThanOrEqual(0);expect(cloud.phases[i]).toBeLessThan(1);}expect([...streams].sort()).toEqual([0,1,2,3,4,5]);expect(cloud.positions.every(Number.isFinite)).toBe(true);});
 it('creates shader streams and reduces their actual submission count',()=>{for(const width of [390,1440]){vi.stubGlobal('innerWidth',width);const scene=new THREE.Scene();const wind=createWind(scene,6);const points=scene.children[0] as THREE.Points;expect(points.geometry.getAttribute('position').count).toBe(width<600?1024:2048);expect(wind.material.uniforms.speed.value).toBe(6);expect(wind.material.depthWrite).toBe(false);wind.setQuality(.5);expect(points.geometry.drawRange.count).toBe(width<600?256:512);wind.setQuality(1);expect(points.geometry.drawRange.count).toBe(width<600?1024:2048);points.geometry.dispose();wind.material.dispose();}vi.unstubAllGlobals();});
 it('rejects invalid populations',()=>{for(const count of [0,-1,1.5,NaN,20001])expect(()=>generateWind(count)).toThrow(RangeError);});
});
